// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi09G865R_T8KzIJ-XYMirONDUj2TSkdc',
    appId: '1:974025291344:web:92f69456cf99ad3e380355',
    messagingSenderId: '974025291344',
    projectId: 'bard-gpt',
    authDomain: 'bard-gpt.firebaseapp.com',
    storageBucket: 'bard-gpt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWbB_eW-TqbF2L8idnAlCtGuImo10R5GM',
    appId: '1:974025291344:android:217aa7e7b32d3886380355',
    messagingSenderId: '974025291344',
    projectId: 'bard-gpt',
    storageBucket: 'bard-gpt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxNOIapa_5S0LC3GAYVMxqrvhYimQUdvw',
    appId: '1:974025291344:ios:449064c5372ff363380355',
    messagingSenderId: '974025291344',
    projectId: 'bard-gpt',
    storageBucket: 'bard-gpt.appspot.com',
    iosClientId: '974025291344-c0bqsa7b2l7ohvhdk6qi8tcnuadi2asg.apps.googleusercontent.com',
    iosBundleId: 'com.bard.chatgpt.hcmus',
  );
}
