// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqKUxe4GwvVYBd9hRUQ_jKDv9ZFEzCEdE',
    appId: '1:86992037195:web:6ac50d7aa6ff8fda6a34ce',
    messagingSenderId: '86992037195',
    projectId: 'voicegpt-63042',
    authDomain: 'voicegpt-63042.firebaseapp.com',
    storageBucket: 'voicegpt-63042.appspot.com',
    measurementId: 'G-MPJRZL6YFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqYKEpq968iPKjojpOQy7dUgEajCBrRtA',
    appId: '1:86992037195:android:42f1a707c117fb596a34ce',
    messagingSenderId: '86992037195',
    projectId: 'voicegpt-63042',
    storageBucket: 'voicegpt-63042.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgzIVqoD14TQ_Niq_SK-8zNcrBPRYLhak',
    appId: '1:86992037195:ios:1289a4f760178eab6a34ce',
    messagingSenderId: '86992037195',
    projectId: 'voicegpt-63042',
    storageBucket: 'voicegpt-63042.appspot.com',
    iosClientId: '86992037195-s778se1sq38avs5d0d7fsr572tibc8bq.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatgpt',
  );
}
