// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALydtzxjejdoeQllz_lwU7RRDZPHceqvI',
    appId: '1:322854016771:android:1ddd8caa3a894200267b36',
    messagingSenderId: '322854016771',
    projectId: 'bardgpt-super-ai-chatbot-cfe0e',
    storageBucket: 'bardgpt-super-ai-chatbot-cfe0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQj6oUIsoqhp8Cf3AqZp4VwR8EwW9F3R4',
    appId: '1:322854016771:ios:d17abf2c5a0d83db267b36',
    messagingSenderId: '322854016771',
    projectId: 'bardgpt-super-ai-chatbot-cfe0e',
    storageBucket: 'bardgpt-super-ai-chatbot-cfe0e.appspot.com',
    iosClientId: '322854016771-7um83e0t8pkgkqdiphe29r3qr85pmiar.apps.googleusercontent.com',
    iosBundleId: 'com.bard.hcmus',
  );
}
